### ISSUE TITLE
serial_number and world_wide_name should be unique

### ISSUE THREAD

**Issue by domsj** [Seagate/kinetic-java#14]
The previous fix for this issue (see https://github.com/Seagate/kinetic-java/issues/5 and https://github.com/Seagate/kinetic-java/commit/06f0103a8d4dbaa72ead0a42f3fdba12bdc7f6c3 ) is insufficient.

In my case I have 2 kinetic simulators running for which the following is true:
- they have the same ip (127.0.0.1)
- they are started on the same port (on different nodes)
- they are started with the same home dir

this sadly enough results in the same world_wide_name (and serial_number) for different instances of the simulator.

One way to fix it would be generating a unique id (guid/uuid) once and persisting it in the home dir of the node. Or you could grab some piece of unique info about the node from somewhere (such as the actual ip address, or the mac address of one of the nics or ...)

The current behaviour is interfering with my test automation... but I can work around it (e.g. by having different home dirs for the simulators on different nodes)

**Comment by chiaming2000** [comment]
Many thanks for the feedback!

A fix is committed to the repo with the suggestion.  A unique uuid is used as world wide name (wwn) for each instance of simulator and the information is persisted under its Kinetic home.
 
https://github.com/Seagate/kinetic-java/commit/37e980fbf9ca12c0801d71ac58984db1ddd15c7c

**Comment by domsj** [comment]
Thanks for the quick response chiaming!
