### ISSUE TITLE
Already in batch mode

### ISSUE THREAD

**Issue by domsj** [Seagate/kinetic-java#15]
Hi, should a client ever recieve this message from the server?
https://github.com/Seagate/kinetic-java/blob/master/kinetic-simulator/src/main/java/com/seagate/kinetic/simulator/internal/BatchOperationHandler.java#L80

Or can it be considered an internal error if I do see it?

A look at the code seems to suggest that 
https://github.com/Seagate/kinetic-java/blob/master/kinetic-simulator/src/main/java/com/seagate/kinetic/simulator/internal/SimulatorEngine.java#L457
should wait until the current batch is finished such that when the init call in BatchOperationHandler should only be done when no other batch is active, unfortunately it doesn't exactly work like that...

**Comment by chiaming2000** [comment]
Hi,

Many thanks for the feedbacks.  A client should never see the message.
Please consider it an internal error if you do see it.

A preliminary fix was committed to address this issue.  Running a simple
verification (5 concurrent threads with a million batch commit for each
thread) did not see any issue raised by the concurrent batch operations.

Thanks.
Chiaming


On Fri, Feb 27, 2015 at 7:34 AM, Jan Doms <notifications@github.com> wrote:

> Hi, should a client ever recieve this message from the server?
>
> https://github.com/Seagate/kinetic-java/blob/master/kinetic-simulator/src/main/java/com/seagate/kinetic/simulator/internal/BatchOperationHandler.java#L80
>
> Or can it be considered an internal error if I do see it?
>
A look at the code seems to suggest that

**Comment by domsj** [comment]
Thanks for the quick response and preliminary fix Chiaming!
